services:
  - type: web
    name: ai-cloud-study-saver
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run code/app.py --server.address 0.0.0.0 --server.port $PORT --server.headless true
    envVars:
      - key: ADMIN_LOGIN_ID
        value: admin
      - key: ADMIN_PASSWORD
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: FIREBASE_KEY_JSON
        sync: false
