services:
  - type: web
    name: AI Cloud Study Saver
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run code/app.py --server.port $PORT
    envVars:
      - key: ADMIN_LOGIN_ID
        value: admin
      - key: ADMIN_PASSWORD
        value: CHANGE_ME
      - key: GROQ_API_KEY
        value: CHANGE_ME
      - key: FIREBASE_KEY_JSON
        value: CHANGE_ME
